# Generated by Django 5.2.2 on 2025-06-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('about', models.TextField()),
                ('languages', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('skills_table', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('resume_projects', models.JSONField(default=list)),
                ('testimonials', models.JSONField(default=list)),
                ('video_urls', models.JSONField(default=list)),
                ('pdf_files', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
